const data = [
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1938,
        name: 'Majestic Sands',
        address: 'Address 1704',
        bathCount: 1,
        bedCount: 3,
        area: '1x2 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3441,
        name: 'Tranquil Gardens',
        address: 'Address 9620',
        bathCount: 4,
        bedCount: 4,
        area: '5x10 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3902,
        name: 'Majestic Sands',
        address: 'Address 4490',
        bathCount: 2,
        bedCount: 1,
        area: '3x9 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2641,
        name: 'Tranquil Gardens',
        address: 'Address 7222',
        bathCount: 3,
        bedCount: 4,
        area: '1x5 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2219,
        name: 'Royal Oasis',
        address: 'Address 4818',
        bathCount: 3,
        bedCount: 1,
        area: '8x7 sq m.',
        location: 'Chicago',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3577,
        name: 'Sapphire Palace',
        address: 'Address 5299',
        bathCount: 4,
        bedCount: 4,
        area: '5x9 sq m.',
        location: 'Chicago',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1159,
        name: 'Sapphire Palace',
        address: 'Address 3141',
        bathCount: 1,
        bedCount: 5,
        area: '1x8 sq m.',
        location: 'Los Angeles',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3648,
        name: 'Golden View',
        address: 'Address 397',
        bathCount: 1,
        bedCount: 1,
        area: '5x2 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2536,
        name: 'Moonlight Manor',
        address: 'Address 1879',
        bathCount: 1,
        bedCount: 1,
        area: '4x6 sq m.',
        location: 'Chicago',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3190,
        name: 'Harmony Shores',
        address: 'Address 3198',
        bathCount: 1,
        bedCount: 2,
        area: '10x10 sq m.',
        location: 'San Francisco',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3512,
        name: 'Tranquil Gardens',
        address: 'Address 8474',
        bathCount: 1,
        bedCount: 5,
        area: '4x7 sq m.',
        location: 'New York',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1934,
        name: 'Azure Coast',
        address: 'Address 8264',
        bathCount: 3,
        bedCount: 2,
        area: '8x3 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2457,
        name: 'Azure Coast',
        address: 'Address 8453',
        bathCount: 1,
        bedCount: 4,
        area: '1x10 sq m.',
        location: 'New York',
        type: 'Houses',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3072,
        name: 'Crystal Retreat',
        address: 'Address 3399',
        bathCount: 3,
        bedCount: 1,
        area: '6x5 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2757,
        name: 'Golden View',
        address: 'Address 8346',
        bathCount: 3,
        bedCount: 2,
        area: '9x6 sq m.',
        location: 'San Francisco',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3172,
        name: 'Golden View',
        address: 'Address 3952',
        bathCount: 4,
        bedCount: 5,
        area: '6x5 sq m.',
        location: 'Chicago',
        type: 'Condos',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3730,
        name: 'Sapphire Palace',
        address: 'Address 3661',
        bathCount: 2,
        bedCount: 1,
        area: '1x10 sq m.',
        location: 'Miami',
        type: 'Apartments',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1780,
        name: 'Azure Coast',
        address: 'Address 6450',
        bathCount: 4,
        bedCount: 4,
        area: '8x8 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1108,
        name: 'Tranquil Gardens',
        address: 'Address 6583',
        bathCount: 3,
        bedCount: 5,
        area: '7x9 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1830,
        name: 'Sunset Haven',
        address: 'Address 3679',
        bathCount: 4,
        bedCount: 2,
        area: '3x7 sq m.',
        location: 'New York',
        type: 'Houses',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1778,
        name: 'Ocean Breeze',
        address: 'Address 9240',
        bathCount: 3,
        bedCount: 3,
        area: '7x10 sq m.',
        location: 'Chicago',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1661,
        name: 'Harmony Shores',
        address: 'Address 1113',
        bathCount: 4,
        bedCount: 1,
        area: '3x6 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1848,
        name: 'Crystal Retreat',
        address: 'Address 9180',
        bathCount: 1,
        bedCount: 3,
        area: '5x8 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3837,
        name: 'Sunset Haven',
        address: 'Address 4457',
        bathCount: 1,
        bedCount: 4,
        area: '1x7 sq m.',
        location: 'San Francisco',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1708,
        name: 'Coral Bay',
        address: 'Address 458',
        bathCount: 4,
        bedCount: 1,
        area: '8x3 sq m.',
        location: 'San Francisco',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1793,
        name: 'Sapphire Palace',
        address: 'Address 4757',
        bathCount: 3,
        bedCount: 3,
        area: '3x6 sq m.',
        location: 'Los Angeles',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3900,
        name: 'Majestic Sands',
        address: 'Address 7357',
        bathCount: 1,
        bedCount: 4,
        area: '10x2 sq m.',
        location: 'San Francisco',
        type: 'Houses',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2670,
        name: 'Coral Bay',
        address: 'Address 8260',
        bathCount: 3,
        bedCount: 1,
        area: '1x9 sq m.',
        location: 'Chicago',
        type: 'Villas',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1531,
        name: 'Grand Plaza',
        address: 'Address 9925',
        bathCount: 2,
        bedCount: 5,
        area: '9x10 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2360,
        name: 'Harmony Shores',
        address: 'Address 2296',
        bathCount: 2,
        bedCount: 1,
        area: '4x2 sq m.',
        location: 'Chicago',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3343,
        name: 'Majestic Sands',
        address: 'Address 7073',
        bathCount: 4,
        bedCount: 2,
        area: '2x2 sq m.',
        location: 'San Francisco',
        type: 'Condos',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2329,
        name: 'Majestic Sands',
        address: 'Address 8346',
        bathCount: 1,
        bedCount: 3,
        area: '2x9 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1408,
        name: 'Royal Oasis',
        address: 'Address 2859',
        bathCount: 2,
        bedCount: 1,
        area: '9x10 sq m.',
        location: 'Chicago',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3482,
        name: 'Enchanted Springs',
        address: 'Address 7428',
        bathCount: 3,
        bedCount: 1,
        area: '1x7 sq m.',
        location: 'New York',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3923,
        name: 'Royal Oasis',
        address: 'Address 992',
        bathCount: 4,
        bedCount: 1,
        area: '10x2 sq m.',
        location: 'San Francisco',
        type: 'Villas',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1229,
        name: 'Whispering Hills',
        address: 'Address 3901',
        bathCount: 3,
        bedCount: 2,
        area: '3x4 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3595,
        name: 'Moonlight Manor',
        address: 'Address 5388',
        bathCount: 1,
        bedCount: 2,
        area: '6x10 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1584,
        name: 'Royal Oasis',
        address: 'Address 796',
        bathCount: 3,
        bedCount: 5,
        area: '5x4 sq m.',
        location: 'Chicago',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3080,
        name: 'Ocean Breeze',
        address: 'Address 2173',
        bathCount: 1,
        bedCount: 1,
        area: '1x3 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3786,
        name: 'Harmony Shores',
        address: 'Address 8194',
        bathCount: 4,
        bedCount: 5,
        area: '5x6 sq m.',
        location: 'Los Angeles',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2078,
        name: 'Royal Oasis',
        address: 'Address 3464',
        bathCount: 4,
        bedCount: 5,
        area: '8x5 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3957,
        name: 'Crystal Retreat',
        address: 'Address 805',
        bathCount: 2,
        bedCount: 1,
        area: '3x10 sq m.',
        location: 'Miami',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1240,
        name: 'Tranquil Gardens',
        address: 'Address 7994',
        bathCount: 4,
        bedCount: 3,
        area: '5x5 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1218,
        name: 'Whispering Hills',
        address: 'Address 6088',
        bathCount: 1,
        bedCount: 5,
        area: '5x5 sq m.',
        location: 'Los Angeles',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1305,
        name: 'Harmony Shores',
        address: 'Address 785',
        bathCount: 3,
        bedCount: 5,
        area: '4x3 sq m.',
        location: 'Miami',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3406,
        name: 'Moonlight Manor',
        address: 'Address 2287',
        bathCount: 4,
        bedCount: 1,
        area: '6x5 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1535,
        name: 'Golden View',
        address: 'Address 5012',
        bathCount: 1,
        bedCount: 1,
        area: '10x5 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2113,
        name: 'Moonlight Manor',
        address: 'Address 4455',
        bathCount: 1,
        bedCount: 1,
        area: '7x10 sq m.',
        location: 'Miami',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2642,
        name: 'Grand Plaza',
        address: 'Address 8474',
        bathCount: 2,
        bedCount: 1,
        area: '4x4 sq m.',
        location: 'San Francisco',
        type: 'Condos',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3446,
        name: 'Crystal Retreat',
        address: 'Address 3298',
        bathCount: 1,
        bedCount: 2,
        area: '9x6 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3060,
        name: 'Sunset Haven',
        address: 'Address 3579',
        bathCount: 3,
        bedCount: 4,
        area: '6x9 sq m.',
        location: 'San Francisco',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1891,
        name: 'Majestic Sands',
        address: 'Address 3924',
        bathCount: 2,
        bedCount: 4,
        area: '10x5 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3489,
        name: 'Tranquil Gardens',
        address: 'Address 7161',
        bathCount: 1,
        bedCount: 3,
        area: '2x10 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2430,
        name: 'Whispering Hills',
        address: 'Address 4638',
        bathCount: 3,
        bedCount: 1,
        area: '9x8 sq m.',
        location: 'Miami',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1144,
        name: 'Azure Coast',
        address: 'Address 4088',
        bathCount: 1,
        bedCount: 2,
        area: '4x2 sq m.',
        location: 'Miami',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3609,
        name: 'Azure Coast',
        address: 'Address 1177',
        bathCount: 2,
        bedCount: 2,
        area: '2x9 sq m.',
        location: 'New York',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1955,
        name: 'Royal Oasis',
        address: 'Address 3899',
        bathCount: 2,
        bedCount: 5,
        area: '6x6 sq m.',
        location: 'Miami',
        type: 'Villas',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2025,
        name: 'Tranquil Gardens',
        address: 'Address 1071',
        bathCount: 1,
        bedCount: 1,
        area: '8x4 sq m.',
        location: 'Miami', type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1560,
        name: 'Majestic Sands',
        address: 'Address 4174',
        bathCount: 3,
        bedCount: 4,
        area: '9x7 sq m.',
        location: 'San Francisco',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3387,
        name: 'Whispering Hills',
        address: 'Address 9733',
        bathCount: 2,
        bedCount: 2,
        area: '6x8 sq m.',
        location: 'San Francisco',
        type: 'Villas',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2976,
        name: 'Coral Bay',
        address: 'Address 5618',
        bathCount: 2,
        bedCount: 5,
        area: '6x5 sq m.',
        location: 'Chicago',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3090,
        name: 'Whispering Hills',
        address: 'Address 6954',
        bathCount: 4,
        bedCount: 3,
        area: '10x5 sq m.',
        location: 'Chicago',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2518,
        name: 'Sapphire Palace',
        address: 'Address 6626',
        bathCount: 1,
        bedCount: 4,
        area: '2x5 sq m.',
        location: 'Chicago',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2897,
        name: 'Whispering Hills',
        address: 'Address 5457',
        bathCount: 1,
        bedCount: 5,
        area: '2x9 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1991,
        name: 'Harmony Shores',
        address: 'Address 6165',
        bathCount: 3,
        bedCount: 1,
        area: '7x7 sq m.',
        location: 'Los Angeles',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2659,
        name: 'Whispering Hills',
        address: 'Address 7023',
        bathCount: 3,
        bedCount: 3,
        area: '4x3 sq m.',
        location: 'San Francisco',
        type: 'Villas',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2115,
        name: 'Azure Coast',
        address: 'Address 2504',
        bathCount: 2,
        bedCount: 4,
        area: '6x8 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3443,
        name: 'Crystal Retreat',
        address: 'Address 5896',
        bathCount: 2,
        bedCount: 4,
        area: '5x6 sq m.',
        location: 'Miami',
        type: 'Villas',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1453,
        name: 'Grand Plaza',
        address: 'Address 9103',
        bathCount: 2,
        bedCount: 3,
        area: '3x3 sq m.',
        location: 'San Francisco',
        type: 'Villas',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3665,
        name: 'Azure Coast',
        address: 'Address 8562',
        bathCount: 4,
        bedCount: 3,
        area: '3x2 sq m.',
        location: 'Chicago',
        type: 'Villas',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3831,
        name: 'Sapphire Palace',
        address: 'Address 9341',
        bathCount: 3,
        bedCount: 1,
        area: '3x1 sq m.',
        location: 'Chicago',
        type: 'Condos',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3990,
        name: 'Majestic Sands',
        address: 'Address 3711',
        bathCount: 3,
        bedCount: 1,
        area: '1x6 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3670,
        name: 'Sapphire Palace',
        address: 'Address 1019',
        bathCount: 4,
        bedCount: 3,
        area: '8x6 sq m.',
        location: 'New York',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1670,
        name: 'Tranquil Gardens',
        address: 'Address 8396',
        bathCount: 3,
        bedCount: 2,
        area: '1x5 sq m.',
        location: 'San Francisco',
        type: 'Condos',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3124,
        name: 'Whispering Hills',
        address: 'Address 2700',
        bathCount: 1,
        bedCount: 5,
        area: '2x10 sq m.',
        location: 'San Francisco',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2274,
        name: 'Grand Plaza',
        address: 'Address 8999',
        bathCount: 1,
        bedCount: 4,
        area: '2x4 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2620,
        name: 'Enchanted Springs',
        address: 'Address 1305',
        bathCount: 3,
        bedCount: 2,
        area: '5x3 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2068,
        name: 'Coral Bay',
        address: 'Address 1977',
        bathCount: 3,
        bedCount: 3,
        area: '1x4 sq m.',
        location: 'Chicago',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3427,
        name: 'Azure Coast',
        address: 'Address 5243',
        bathCount: 2,
        bedCount: 3,
        area: '8x2 sq m.',
        location: 'New York',
        type: 'Villas',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3640,
        name: 'Sunset Haven',
        address: 'Address 1458',
        bathCount: 1,
        bedCount: 3,
        area: '6x5 sq m.',
        location: 'Miami',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3569,
        name: 'Golden View',
        address: 'Address 1691',
        bathCount: 4,
        bedCount: 5,
        area: '4x3 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3220,
        name: 'Coral Bay',
        address: 'Address 9695',
        bathCount: 1,
        bedCount: 4,
        area: '5x8 sq m.',
        location: 'San Francisco',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1206,
        name: 'Crystal Retreat',
        address: 'Address 1728',
        bathCount: 4,
        bedCount: 2,
        area: '2x10 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1589,
        name: 'Moonlight Manor',
        address: 'Address 9822',
        bathCount: 4,
        bedCount: 5,
        area: '1x5 sq m.',
        location: 'Chicago',
        type: 'Condos',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1286,
        name: 'Moonlight Manor',
        address: 'Address 302',
        bathCount: 3,
        bedCount: 2,
        area: '3x1 sq m.',
        location: 'New York',
        type: 'Houses',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3848,
        name: 'Tranquil Gardens',
        address: 'Address 2925',
        bathCount: 4,
        bedCount: 4,
        area: '8x5 sq m.',
        location: 'New York',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2924,
        name: 'Grand Plaza',
        address: 'Address 3973',
        bathCount: 1,
        bedCount: 4,
        area: '6x8 sq m.',
        location: 'San Francisco',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1880,
        name: 'Whispering Hills',
        address: 'Address 7946',
        bathCount: 4,
        bedCount: 4,
        area: '7x3 sq m.',
        location: 'Los Angeles',
        type: 'Houses',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3085,
        name: 'Sunset Haven',
        address: 'Address 8427',
        bathCount: 3,
        bedCount: 4,
        area: '6x2 sq m.',
        location: 'Los Angeles',
        type: 'Condos',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3964,
        name: 'Majestic Sands',
        address: 'Address 4253',
        bathCount: 1,
        bedCount: 1,
        area: '1x10 sq m.',
        location: 'Los Angeles',
        type: 'Apartments',
        dateAvailable: '2023-08-05'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3409,
        name: 'Moonlight Manor',
        address: 'Address 9865',
        bathCount: 2,
        bedCount: 5,
        area: '10x6 sq m.',
        location: 'Miami',
        type: 'Villas',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2058,
        name: 'Harmony Shores',
        address: 'Address 2834',
        bathCount: 4,
        bedCount: 5,
        area: '6x8 sq m.',
        location: 'Chicago',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2481,
        name: 'Royal Oasis',
        address: 'Address 8821',
        bathCount: 3,
        bedCount: 1,
        area: '8x1 sq m.',
        location: 'Miami',
        type: 'Houses',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2400,
        name: 'Coral Bay',
        address: 'Address 3063',
        bathCount: 2,
        bedCount: 3,
        area: '8x9 sq m.',
        location: 'New York',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2175,
        name: 'Azure Coast',
        address: 'Address 9671',
        bathCount: 1,
        bedCount: 1,
        area: '4x5 sq m.',
        location: 'Los Angeles',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2892,
        name: 'Moonlight Manor',
        address: 'Address 6127',
        bathCount: 2,
        bedCount: 1,
        area: '7x3 sq m.',
        location: 'Miami',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 3999,
        name: 'Ocean Breeze',
        address: 'Address 6329',
        bathCount: 3,
        bedCount: 1,
        area: '4x8 sq m.',
        location: 'New York',
        type: 'Apartments',
        dateAvailable: '2023-06-15'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2638,
        name: 'Harmony Shores',
        address: 'Address 4875',
        bathCount: 3,
        bedCount: 5,
        area: '5x5 sq m.',
        location: 'Los Angeles',
        type: 'Apartments',
        dateAvailable: '2023-07-10'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 1507,
        name: 'Sapphire Palace',
        address: 'Address 4267',
        bathCount: 3,
        bedCount: 1,
        area: '3x7 sq m.',
        location: 'Chicago',
        type: 'Apartments',
        dateAvailable: '2023-05-23'
    },
    {
        src: 'https://img.freepik.com/free-photo/blue-house-with-blue-roof-sky-background_1340-25953.jpg',
        price: 2469,
        name: 'Whispering Hills',
        address: 'Address 3092',
        bathCount: 3,
        bedCount: 3,
        area: '9x7 sq m.',
        location: 'San Francisco',
        type: 'Condos',
        dateAvailable: '2023-07-10'
    }
]

export default data;